services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "url_service"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./database-scripts:/docker-entrypoint-initdb.d
      - ./sql_data:/var/lib/postgres
    ports:
      - "172.17.0.1:5432:5432"

  app:
    image: thxtomslf/url-service:url-service
    restart: always
    environment:
        POSTGRES_DB: "url_service"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"