on: push

jobs:

  build:
    runs-on: ubuntu-latest
    container: thxtomslf/url-service
    steps:
      - run: make build

  test:
    runs-on: ubuntu-latest
    container: thxtomslf/url-service
    steps:
      - run: make test